CREATE TABLE song(songID INT primary key AUTO_INCREMENT, title varchar(50) not null, artist varchar(50) not null);
CREATE TABLE contributors(cID INT primary key AUTO_INCREMENT, name varchar(50) not null, contribution varchar(50) not null);
CREATE TABLE kFile(kID INT primary key AUTO_INCREMENT, songID INT not null, filename varchar(50) not null, foreign key(songID) references song(songID));
CREATE TABLE user(uID INT primary key AUTO_INCREMENT, name varchar(50) not null);
CREATE TABLE contributions(songID INT, cID INT, primary key(songID, cID), foreign key(songID) references song(songID), foreign key(cID) references contributors(cID));
CREATE TABLE submission(kID INT, uID INT, time INT not null, amtPaid INT, played BOOLEAN DEFAULT FALSE,  primary key(kID, uID), foreign key(uID) references user(uID));

INSERT INTO song(title, artist) VALUES 
	('Total Eclipse of the Heart', 'Bonnie Tyler'),
	('Jumper', 'Third Eye Blind'),
	('Semi-Charmed Life', 'Third Eye Blind'),
	('Hows it Gonna Be', 'Third Eye Blind'),
	('Just A Friend', 'Biz Markie'),
	('I Miss You', 'Blink 182'),
	('Adams Song', 'Blink 182'),
	('Dont Stop Me Now', 'Queen'),
	('Bohemian Rhapsody', 'Queen'),
	('Sweet Caroline', 'Niel Diamond'),
	('Creep', 'Radiohead'),
	('Karma Police', 'Radiohead'),
	('Mr. Brightside', 'The Killers'),
	('When You Were Young', 'The Killers');

INSERT INTO contributors(name, contribution) VALUES
	('Bonnie Tyler', 'Lead Vocals'),
	('Jim Steinman', 'Lyricist'),
	('Stephan Jenkins', 'Lyricist'),
	('Stephan Jenkins', 'Lead Vocals'),
	('Stephan Jenkins', 'Guitar'),
	('Stephan Jenkins', 'Percussion'),
	('Kevin Cadogan', 'Lyricist'),
	('Kevin Cadogan', 'Lead Guitar'),
	('Kevin Cadogan', 'Autoharp'),
	('Kevin Cadogan', 'Backing Vocals'),
	('Arion Salazar', 'Bass Guitar'),
	('Arion Salazar', 'Piano'),
	('Arion Salazar', 'Backing Vocals'),
	('Brad Hargreaves', 'Drums'),
	('Ronald Murray', 'Lyricist'),
	('Biz Markie', 'Lead Vocals'),
	('Biz Markie', 'Producer'),
	('Tom DeLonge', 'Lyricist'),
	('Tom DeLonge', 'Lead Vocals'),
	('Mark Hoppus', 'Lyricist'),
	('Mark Hoppus', 'Bass Guitar'),
	('Mark Hoppus', 'Vocals'),
	('Travis Barker', 'Lyricist'),
	('Travis Barker', 'Drums'),
	('Jerry Finn', 'Producer'),
	('Freddie Mercury', 'Lyricist'),
	('Freddie Mercury', 'Lead Vocals'),
	('Freddie Mercury', 'Backing Vocals'),
	('Freddie Mercury', 'Piano'),
	('Brian May', 'Electric Guitar'),
	('Brian May', 'Backing Vocals'),
	('Roger Taylor', 'Percussion'),
	('Roger Taylor', 'Backing Vocals'),
	('John Deacon', 'Bass Guitar'),
	('Roy Thomas Baker', 'Producer'),
	('Niel Diamond', 'Lyricist'),
	('Niel Diamond', 'Guitar'),
	('Tommy Cogbill', 'Producer'),
	('Chips Moman', 'Producer'),
	('Albert Hammond', 'Lyricist'),
	('Mike Hazlewoof', 'Lyricist'),
	('Thom Yorke', 'Lead Vocals'),
	('Thom Yorke', 'Lyricist'),
	('Colin Greenwood', 'Bass Guitar'),
	('Colin Greenwood', 'Lyricist'),
	('Jonny Greenwood', 'Lyricist'),
	('Jonny Greenwood', 'Guitar'),
	('Jonny Greenwood', 'Piano'),
	('Ed O\'Brien', 'Rhythm Guitar'),
	('Ed O\'Brien', 'Lyricist'),
	('Philip Selway', 'Drums'),
	('Philip Selway', 'Lyricist'),
	('Brandon Flowers', 'Lead Vocals'),
	('Brandon Flowers', 'Keyboard'),
	('Brandon Flowers', 'Bass'),
	('Brandon Flowers', 'Lyricist'),
	('Dave Keuning', 'Lead Guitar'),
	('Dave Keuning', 'Backing Vocals'),
	('Dave Keuning', 'Lyricist'),
	('Mark Stoermer', 'Bass'),
	('Mark Stoermer', 'Rhythm Guitar'),
	('Mark Stoermer', 'Lyricist'),
	('Ronnie Vannucci Jr', 'Percussion'),
	('Ronnie Vannucci Jr', 'Lyricist'),
	('Alan Moulder', 'Producer');

INSERT INTO contributions(songID, cID) VALUES
	(1, 1), (1, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 8), (2, 10), (2, 11), (2, 12), (2, 13), (2, 14),
	(3, 3), (3, 4), (3, 5), (3, 6), (3, 8), (3, 10), (3, 11), (3, 12), (3, 13), (3, 14), (4, 3), (4, 7),
	(4, 4), (4, 8), (4, 9), (4, 10), (4, 11), (4, 13), (5, 15), (5, 16), (5, 17), (6, 18), (6, 19), (6, 20),
    (6, 21), (6, 22), (6, 23), (6, 24), (6, 25), (7, 18), (7, 20), (7, 19), (7, 21), (7, 22), (7, 24), (7, 25), 
    (8, 26), (8, 27), (8, 28), (8, 29), (8, 30), (8, 31), (8, 32), (8, 33), (8, 34), (8, 35), (9, 26), (9, 27),
	(9, 28), (9, 29), (9, 30), (9, 31), (9, 32), (9, 33), (9, 34), (9, 35), (10, 36), (10, 37), (10, 38), (10, 39),
	(11, 40), (11, 41), (11, 42), (11, 44), (11, 47), (11, 48), (11, 49), (11, 51), (12, 43), (12, 45), (12, 46),
	(12, 50), (12, 52), (12, 42), (12, 47), (12, 48), (12, 44), (12, 49), (12, 51), (13, 53), (13, 54), (13, 55),
	(13, 56), (13, 57), (13, 58), (13, 59), (13, 60), (13, 61), (13, 62), (13, 64), (14, 53), (14, 54), (14, 55),
	(14, 56), (14, 57), (14, 58), (14, 59), (14, 60), (14, 61), (14, 62), (14, 64), (14, 65);


INSERT INTO kFile(songID, filename) VALUES
	('1', 'totaleclipse_1.wav'),
	('1', 'totaleclipse_2.mp3'), 
	('2', 'jumper.mp3'), 
	('3', 'semicharmed.mp3'), 
	('3', 'semicharmed_2.mp3'), 
	('3', 'semicharmed.wav'), 
	('4', 'howitsgonnabe_1.mp3'), 
	('4', 'howitsgonnabe_2.mp3'), 
	('5', 'justafriend_biz.mp3'), 
	('6', 'missyou_blink_1.wav'),
    ('7', 'adamssong_blink.mp3'), 
    ('7', 'adamssong.wav'), 
    ('8', 'dont_stop_me_now.mp3'), 
    ('8', 'dontstopmenow.wav'), 
    ('9', 'bohemianrhapsody.mp3'), 
    ('10', 'sweetcaroline.wav'), 
    ('10', 'overplayedsong-sweetcaroline.mp3'), 
    ('10', 'sweet_caroline_2.mp3'), 
    ('11', 'creep_radiohead.mp3'), 
    ('12', 'karmapolice.mp3'),
    ('13', 'mrbrightside.wav'), 
    ('14', 'whenuwereyoung.wav'), 
    ('14', 'whenyouwereyoung.mp3');
